from enum import Enum


class EventActionType(Enum):
    JUMPSHOT = 1
    LOST_BALL_TURNOVER = 2
    TRAVELING_TURNOVER_OR_OFF_FOUL = 4
    LAYUP = 5
    DUNK = 7
    FREE_THROW_1_1 = 10
    FREE_THROW_1_2 = 11
    FREE_THROW_2_2 = 12
    OUT_OF_BOUNDS = 40
    BLOCK_STEAL = 41
    DRIVING_LAYUP = 42
    RUNNING_DUNK = 50
    ALLEY_OOP_DUNK = 52
    HOOK_SHOT = 55
    DRIVING_HOOK_SHOT = 57
    TURNAROUND_HOOK_SHOT = 58
    JUMP_BANK_SHOT = 66
    FINGER_ROLL_LAYUP = 71
    PUTBACK_LAYUP = 72
    TIP_LAYOUP = 92
    CUTTING_DUNK_SHOT = 108
